/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { defineComponent, h, computed } from 'vue'
import {
  Plus,
  Search,
  Edit3,
  Trash2,
  Copy,
  CheckCircle,
  PauseCircle,
  ChevronLeft,
  ChevronRight,
  FolderOpen,
  Folder,
  Upload,
  Download,
  Database,
  Sync,
  Home,
  ArrowBack,
  Close,
  Info,
  AlertTriangle,
  Check,
  Minus,
  ToggleLeft,
  ToggleRight,
  Settings,
  FileJson,
  UploadCloud,
  DownloadCloud,
  Component,
  HelpCircle,
  Image,
  X,
  List,
  Appstore,
  Sparkles,
  Grid,
  MapPin,
  RefreshCw,
  Users,
  SmartToy,
  Key,
  CorporateFare,
  Monitor,
  VerifiedUser,
  AccountTree,
  Hub,
  TravelExplore,
  FolderOff,
  DatabaseOff,
  Menu,
  Settings2,
  PanelLeft,
  FileCode,
  FileText,
  Save,
  Send,
  Mail,
  Phone,
  MessageSquare,
  Bell,
  Calendar,
  Clock,
  Map,
  Star,
  Heart,
  Bookmark,
  Share2,
  ExternalLink,
  Link,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Filter,
  SortAsc,
  SortDesc,
  MoreVertical,
  MoreHorizontal,
  AlertCircle,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Octagon,
  Diamond,
  Zap,
  Activity,
  BarChart2,
  PieChart,
  TrendingUp,
  TrendingDown,
  Award,
  Target,
  Crosshair,
  Compass,
  Navigation,
  Flag,
  BookmarkPlus,
  BookmarkMinus,
  Archive,
  Inbox,
  Layers,
  Box,
  Package,
  Truck,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Percent,
  Hash,
  AtSign,
  Paperclip,
  Mic,
  MicOff,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Shuffle,
  Repeat,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  BatteryCharging,
  Power,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Wind,
  Thermometer,
  Droplets,
  Snowflake,
  Sunrise,
  Sunset,
  Globe,
  MapPin as MapPinIcon,
  Navigation2,
  Compass2,
  Anchor,
  Ship,
  Plane,
  Train,
  Car,
  Bike,
  Walk,
  Coffee,
  Utensils,
  Pizza,
  Beer,
  Wine,
  Cake,
  Gift,
  ShoppingBag,
  Store,
  Warehouse,
  Factory,
  Building,
  Building2,
  Landmark,
  Castle,
  Church,
  School,
  Hospital,
  Stethoscope,
  Pill,
  Syringe,
  Thermometer as ThermometerIcon,
  Activity as ActivityIcon,
  HeartPulse,
  Brain,
  Eye as EyeIcon,
  Ear,
  Nose,
  Smile,
  Frown,
  Meh,
  Angry,
  Surprised,
  Tired,
  Sleep,
  Dizzy,
  Flame,
  Droplet,
  Leaf,
  TreePine,
  TreeDeciduous,
  Flower2,
  Bug,
  Fish,
  Bird,
  Cat,
  Dog,
  Rabbit,
  Squirrel,
  Turtle,
  Snake,
  Frog,
  Bug as BugIcon,
  Magnet,
  Sparkles as SparklesIcon,
  Wand2,
  Magic,
  Palette,
  Brush,
  Paintbrush,
  PenTool,
  Pencil,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Indent,
  Outdent,
  ListOrdered,
  Quote,
  Code,
  Terminal,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Twitter,
  Facebook,
  Instagram,
  Linkedin,
  Youtube,
  Chrome,
  Firefox,
  Safari,
  Edge,
  Codepen,
  Codesandbox,
  Figma,
  Dribbble,
  Behance,
  Trello,
  Slack,
  Discord,
  Twitch,
  Spotify,
  Apple,
  Windows,
  Linux,
  Terminal as TerminalIcon,
  Cpu,
  HardDrive,
  Server,
  Database as DatabaseIcon,
  Cloud as CloudIcon,
  CloudOff,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning as CloudLightningIcon,
  CloudMoon,
  CloudSnow as CloudSnowIcon,
  CloudSun,
  Eclipse,
  Moon as MoonIcon,
  Sun as SunIcon,
  Star as StarIcon,
  StarHalf,
  StarOff,
  Heart as HeartIcon,
  HeartOff,
  ThumbsUp,
  ThumbsDown,
  MessageCircle,
  MessageSquare as MessageSquareIcon,
  Phone as PhoneIcon,
  PhoneOff,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOutgoing,
  Mail as MailIcon,
  MailCheck,
  MailX,
  MailPlus,
  MailMinus,
  Send as SendIcon,
  SendHorizontal,
  Inbox as InboxIcon,
  Inbox as InboxIcon2,
  Archive as ArchiveIcon,
  Trash as TrashIcon,
  Trash2 as Trash2Icon,
  Edit as EditIcon,
  Edit2 as Edit2Icon,
  Edit3 as Edit3Icon,
  Pen as PenIcon,
  PenLine,
  PenTool as PenToolIcon,
  Pencil as PencilIcon,
  PencilLine,
  PencilRuler,
  Eraser,
  Scissors,
  Copy as CopyIcon,
  Clipboard,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardPaste,
  ClipboardX,
  File,
  File2,
  FileText as FileTextIcon,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  FileOutput,
  Folder as FolderIcon,
  FolderMinus,
  FolderPlus,
  FolderX,
  FolderTree,
  FolderOpen as FolderOpenIcon,
  Image as ImageIcon,
  ImageOff,
  Camera,
  CameraOff,
  Video,
  VideoOff,
  Film,
  Clapperboard,
  Tv,
  Monitor as MonitorIcon,
  MonitorOff,
  MonitorPlay,
  Smartphone,
  Tablet,
  Watch,
  Speaker,
  Radio,
  Headphones,
  Volume as VolumeIcon,
  Volume1,
  Volume2 as Volume2Icon,
  VolumeX as VolumeXIcon,
  Mic as MicIcon,
  MicOff as MicOffIcon,
  Music,
  Music2,
  Music3,
  Music4,
  Play as PlayIcon,
  PlayCircle,
  PlaySquare,
  Pause as PauseIcon,
  PauseCircle as PauseCircleIcon,
  PauseSquare,
  StopCircle,
  SkipForward as SkipForwardIcon,
  SkipBack as SkipBackIcon,
  Rewind,
  FastForward,
  Shuffle as ShuffleIcon,
  Repeat as RepeatIcon,
  Repeat1,
  Repeat2,
  ChevronUp,
  ChevronDown,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpCircle,
  ArrowDownCircle,
  ArrowLeftCircle,
  ArrowRightCircle,
  ArrowUpSquare,
  ArrowDownSquare,
  ArrowLeftSquare,
  ArrowRightSquare,
  RotateCcw,
  RotateCw,
  RefreshCcw,
  RefreshCw as RefreshCwIcon,
  Reload,
  Loader,
  Loader2,
  Power as PowerIcon,
  PowerOff,
  Zap as ZapIcon,
  ZapOff,
  Battery as BatteryIcon,
  BatteryCharging as BatteryChargingIcon,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  BatteryWarning,
  Wifi as WifiIcon,
  WifiOff as WifiOffIcon,
  Bluetooth as BluetoothIcon,
  BluetoothSearching,
  BluetoothOff,
  Signal,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SignalZero,
  Cast,
  Airplay,
  Chromecast,
  Tv2,
  MonitorSpeaker,
  Radar,
  Rss,
  Radio as RadioIcon,
  Podcast,
  Mic2,
  Headphones as HeadphonesIcon,
  Headset,
  AudioLines,
  AudioWaveform,
  CircleDot,
  Circle as CircleIcon,
  Circle as CircleIcon2,
  Circle as CircleIcon3,
  Square as SquareIcon,
  Square as SquareIcon2,
  Square as SquareIcon3,
  Triangle as TriangleIcon,
  Pentagon,
  Hexagon as HexagonIcon,
  Octagon as OctagonIcon,
  Diamond as DiamondIcon,
  Diamond as DiamondIcon2,
  Gem,
  Crown,
  Shield,
  ShieldCheck,
  ShieldOff,
  ShieldAlert,
  Lock as LockIcon,
  LockOpen,
  Unlock as UnlockIcon,
  Key as KeyIcon,
  KeyRound,
  KeySquare,
  Fingerprint,
  Scan,
  ScanLine,
  QrCode,
  Barcode,
  CreditCard as CreditCardIcon,
  Wallet,
  Banknote,
  Coins,
  Receipt,
  Calculator,
  DollarSign as DollarSignIcon,
  Percent as PercentIcon,
  Hash as HashIcon,
  AtSign as AtSignIcon,
  Link as LinkIcon,
  Link2,
  Link2Off,
  Unlink,
  ExternalLink as ExternalLinkIcon,
  Clipboard as ClipboardIcon,
  Paperclip as PaperclipIcon,
  MapPin as MapPinIcon2,
  Navigation as NavigationIcon,
  Navigation2 as Navigation2Icon,
  Compass as CompassIcon,
  Globe as GlobeIcon,
  Globe2,
  Map as MapIcon,
  Layers as LayersIcon,
  Box as BoxIcon,
  Package as PackageIcon,
  PackageCheck,
  PackageMinus,
  PackageOpen,
  PackagePlus,
  PackageSearch,
  PackageX,
  Truck as TruckIcon,
  Ship as ShipIcon,
  Plane as PlaneIcon,
  Train as TrainIcon,
  Car as CarIcon,
  Bike as BikeIcon,
  Walk as WalkIcon,
  Bus,
  Fuel,
  ParkingCircle,
  ParkingSquare,
  Milestone,
  Flag as FlagIcon,
  FlagTriangleRight,
  Bookmark as BookmarkIcon,
  BookmarkMinus as BookmarkMinusIcon,
  BookmarkPlus as BookmarkPlusIcon,
  Heart as HeartIcon2,
  HeartOff as HeartOffIcon,
  ThumbsUp as ThumbsUpIcon,
  ThumbsDown as ThumbsDownIcon,
  Smile as SmileIcon,
  Frown as FrownIcon,
  Meh as MehIcon,
  Angry as AngryIcon,
  Surprised as SurprisedIcon,
  Tired as TiredIcon,
  Dizzy as DizzyIcon,
  Laugh,
  Cry,
  Angry as AngryIcon2,
  Flame as FlameIcon,
  Droplet as DropletIcon,
  Droplets as DropletsIcon,
  Leaf as LeafIcon,
  TreePine as TreePineIcon,
  TreeDeciduous as TreeDeciduousIcon,
  Flower2 as Flower2Icon,
  Flower,
  Flower as FlowerIcon2,
  Bug as BugIcon2,
  Fish as FishIcon,
  Bird as BirdIcon,
  Cat as CatIcon,
  Dog as DogIcon,
  Rabbit as RabbitIcon,
  Squirrel as SquirrelIcon,
  Turtle as TurtleIcon,
  Snake as SnakeIcon,
  Frog as FrogIcon,
  Egg,
  EggFried,
  Milk,
  Cookie,
  Croissant,
  Sandwich,
  Soup,
  Salad,
  IceCream,
  IceCreamCone,
  Cherry,
  Apple,
  Grape,
  Banana,
  Orange,
  Lemon,
  Plum,
  Peach,
  Pear,
  Melon,
  Watermelon,
  Strawberry,
  Blueberry,
  Raspberry,
  Pineapple,
  Mango,
  Avocado,
  Coconut,
  Kiwi,
  Tomato,
  Carrot,
  Corn,
  Broccoli,
  Lettuce,
  Cucumber,
  Pepper,
  Onion,
  Garlic,
  Potato,
  SweetPotato,
  Radish,
  Mushroom,
  Eggplant,
  Bean,
  Pea,
  Nut,
  Wheat,
  Rice,
  Bread,
  Toast,
  Croissant as CroissantIcon,
  Baguette,
  Donut,
  Bagel,
  Pretzel,
  Cheese,
  Butter,
  Milk as MilkIcon,
  Yogurt,
  Cream,
  Honey,
  Jam,
  Sauce,
  Ketchup,
  Mustard,
  Mayonnaise,
  Vinegar,
  Oil,
  Salt,
  Pepper as PepperIcon,
  Spice,
  Herb,
  Basil,
  Mint,
  Rosemary,
  Thyme,
  Oregano,
  Parsley,
  Cilantro,
  Dill,
  Chive,
  Sage,
  BayLeaf,
  Cinnamon,
  Ginger,
  Turmeric,
  Saffron,
  Cumin,
  Coriander,
  Paprika,
  Chili,
  Curry,
  Vanilla,
  Chocolate,
  Cocoa,
  Coffee as CoffeeIcon,
  Tea,
  Juice,
  Water,
  Soda,
  Beer as BeerIcon,
  Wine as WineIcon,
  Champagne,
  Cocktail,
  Whiskey,
  Vodka,
  Rum,
  Gin,
  Brandy,
  Liqueur,
  Milk as MilkIcon2,
  Juice as JuiceIcon,
  Water as WaterIcon,
  Soda as SodaIcon,
  Ice,
  Lemon as LemonIcon,
  Lime,
  Orange as OrangeIcon,
  Grape as GrapeIcon,
  Strawberry as StrawberryIcon,
  Cherry as CherryIcon,
  Apple as AppleIcon,
  Banana as BananaIcon,
  Coconut as CoconutIcon,
  Pineapple as PineappleIcon,
  Mango as MangoIcon,
  Peach as PeachIcon,
  Pear as PearIcon,
  Plum as PlumIcon,
  Kiwi as KiwiIcon,
  Avocado as AvocadoIcon,
  Tomato as TomatoIcon,
  Corn as CornIcon,
  Carrot as CarrotIcon,
  Pepper as PepperIcon2,
  Mushroom as MushroomIcon,
  Eggplant as EggplantIcon,
  Potato as PotatoIcon,
  Onion as OnionIcon,
  Garlic as GarlicIcon,
  Bean as BeanIcon,
  Pea as PeaIcon,
  Nut as NutIcon,
  Bread as BreadIcon,
  Pizza as PizzaIcon,
  Sandwich as SandwichIcon,
  Burger,
  HotDog,
  FrenchFries,
  Noodles,
  Sushi,
  Taco,
  Burrito,
  Salad as SaladIcon,
  Soup as SoupIcon,
  Cake as CakeIcon,
  Cookie as CookieIcon,
  Donut as DonutIcon,
  IceCream as IceCreamIcon,
  Candy,
  Lollipop,
  Chocolate as ChocolateIcon,
  Cheese as CheeseIcon,
  Butter as ButterIcon,
  Apple as AppleIcon2,
  Cherry as CherryIcon2,
  Grape as GrapeIcon2,
  Banana as BananaIcon2,
  Orange as OrangeIcon2,
  Lemon as LemonIcon2,
  Strawberry as StrawberryIcon2,
  Watermelon as WatermelonIcon,
  Peach as PeachIcon2,
  Pear as PearIcon2,
  Plum as PlumIcon2,
  Kiwi as KiwiIcon2,
  Avocado as AvocadoIcon2,
  Coconut as CoconutIcon2,
  Pineapple as PineappleIcon2,
  Mango as MangoIcon2,
  Melon as MelonIcon,
  Fig,
  Pomegranate,
  Date,
  Olive,
  Berry,
  Cranberry,
  Raspberry as RaspberryIcon,
  Blueberry as BlueberryIcon,
  Blackberry,
  Gooseberry,
  Currant,
  Elderberry,
  Mulberry,
  Boysenberry,
  Loganberry,
  Cloudberry,
  Lingonberry,
  Crowberry,
  Bearberry,
  Wintergreen,
  Juniper,
  SeaBuckthorn,
  Goumi,
  Honeyberry,
  Haskap,
  Saskatoon,
  Serviceberry,
  Chokecherry,
  Buffaloberry,
  Snowberry,
  Wolfberry,
  Goji,
  Acai,
  CamuCamu,
  Maqui,
  Jabuticaba,
  Cupuacu,
  Mangosteen,
  Durian,
  Rambutan,
  Lychee,
  Longan,
  Jackfruit,
  Durian as DurianIcon,
  Mangosteen as MangosteenIcon,
  Rambutan as RambutanIcon,
  Lychee as LycheeIcon,
  Longan as LonganIcon,
  Jackfruit as JackfruitIcon,
  PassionFruit,
  DragonFruit,
  Guava,
  Papaya,
  Starfruit,
  Persimmon,
  Pomegranate as PomegranateIcon,
  Fig as FigIcon,
  Date as DateIcon,
  Olive as OliveIcon,
  Berry as BerryIcon,
  Cranberry as CranberryIcon,
  Blackberry as BlackberryIcon,
  Gooseberry as GooseberryIcon,
  Currant as CurrantIcon,
  Elderberry as ElderberryIcon,
  Mulberry as MulberryIcon,
  Boysenberry as BoysenberryIcon,
  Loganberry as LoganberryIcon,
  Cloudberry as CloudberryIcon,
  Lingonberry as LingonberryIcon,
  Crowberry as CrowberryIcon,
  Bearberry as BearberryIcon,
  Wintergreen as WintergreenIcon,
  Juniper as JuniperIcon,
  SeaBuckthorn as SeaBuckthornIcon,
  Goumi as GoumiIcon,
  Honeyberry as HoneyberryIcon,
  Haskap as HaskapIcon,
  Saskatoon as SaskatoonIcon,
  Serviceberry as ServiceberryIcon,
  Chokecherry as ChokecherryIcon,
  Buffaloberry as BuffaloberryIcon,
  Snowberry as SnowberryIcon,
  Wolfberry as WolfberryIcon,
  Goji as GojiIcon,
  Acai as AcaiIcon,
  CamuCamu as CamuCamuIcon,
  Maqui as MaquiIcon,
  Jabuticaba as JabuticabaIcon,
  Cupuacu as CupuacuIcon,
} from 'lucide-vue-next'

// Material Icons 到 Lucide 图标的映射
const ICON_MAP: Record<string, any> = {
  add: Plus,
  search: Search,
  edit: Edit3,
  edit_square: Edit3,
  delete: Trash2,
  delete_outline: Trash2,
  content_copy: Copy,
  check_circle: CheckCircle,
  check_circle_outline: CheckCircle,
  pause_circle: PauseCircle,
  pause_circle_outline: PauseCircle,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  folder_open: FolderOpen,
  folder: Folder,
  upload: Upload,
  upload_file: Upload,
  download: Download,
  download_done: Download,
  database: Database,
  sync: Sync,
  home: Home,
  arrow_back: ArrowBack,
  close: Close,
  info: Info,
  info_outline: Info,
  warning: AlertTriangle,
  warning_amber: AlertTriangle,
  check: Check,
  remove: Minus,
  toggle_off: ToggleLeft,
  toggle_on: ToggleRight,
  settings: Settings,
  settings_suggest: Settings,
  file_open: FileJson,
  upload_cloud: UploadCloud,
  download_cloud: DownloadCloud,
  component: Component,
  help: HelpCircle,
  help_outline: HelpCircle,
  image: Image,
  close_fullscreen: X,
  list: List,
  grid_view: Grid,
  sparkles: Sparkles,
  precision_manufacturing: Settings,
  move_up: Upload,
  api: Globe,
  sell: Tag,
  account_tree: Network,
  smart_toy: Bot,
  corporate_fare: Building2,
  key: KeyRound,
  hub: Network,
  verified_user: ShieldCheck,
  monitoring: Activity,
  dns: Database,
  travel_explore: Compass,
  folder_off: FolderOff,
  database_off: DatabaseOff,
  menu: Menu,
  tune: Sliders,
  code: Code,
  file_code: FileCode,
  save: Save,
  send: Send,
  email: Mail,
  phone: Phone,
  chat: MessageSquare,
  notifications: Bell,
  event: Calendar,
  schedule: Clock,
  place: MapPin,
  star: Star,
  favorite: Heart,
  bookmark: Bookmark,
  share: Share2,
  open_in_new: ExternalLink,
  link: Link,
  lock: Lock,
  lock_open: Unlock,
  visibility: Eye,
  visibility_off: EyeOff,
  filter_list: Filter,
  sort: ArrowUpDown,
  more_vert: MoreVertical,
  more_horiz: MoreHorizontal,
  error: AlertCircle,
  circle: Circle,
  crop_square: Square,
  change_history: Triangle,
  hexagon: Hexagon,
  blur_on: Circle,
  scatter_plot: Circle,
  bubbles: Circle,
  local_fire_department: Flame,
  water_drop: Droplet,
  eco: Leaf,
  forest: TreePine,
  yard: Flower2,
  bug_report: Bug,
  pets: Cat,
  smart_toy: Bot,
  magnet: Magnet,
  auto_fix_high: Wand2,
  brush: Paintbrush,
  format_paint: Paintbrush,
  pen_tool: PenTool,
  edit_note: Pencil,
  title: Type,
  format_bold: Bold,
  format_italic: Italic,
  format_underlined: Underline,
  format_strikethrough: Strikethrough,
  format_align_left: AlignLeft,
  format_align_center: AlignCenter,
  format_align_right: AlignRight,
  format_align_justify: AlignJustify,
  format_indent_increase: Indent,
  format_indent_decrease: Outdent,
  format_list_numbered: ListOrdered,
  format_quote: Quote,
  code: Code,
  terminal: Terminal,
  git_branch: GitBranch,
  commit: GitCommit,
  merge_type: GitMerge,
  pull_request: GitPullRequest,
  cloud: Cloud,
  cloud_queue: Cloud,
  cloud_off: CloudOff,
  cloud_download: Download,
  cloud_upload: Upload,
  device_thermostat: Thermometer,
  humidity_percent: Droplets,
  ac_unit: Snowflake,
  wb_sunny: Sun,
  dark_mode: Moon,
  nightlight: Moon,
  light_mode: Sun,
  wb_twilight: Sunrise,
  sunset: Sunset,
  pin_drop: MapPin,
  navigation: Navigation,
  explore: Compass,
  anchor: Anchor,
  directions_boat: Ship,
  flight: Plane,
  train: Train,
  directions_car: Car,
  directions_bike: Bike,
  directions_walk: Walk,
  local_cafe: Coffee,
  restaurant: Utensils,
  local_pizza: Pizza,
  local_bar: Beer,
  wine_bar: Wine,
  cake: Cake,
  redeem: Gift,
  shopping_bag: ShoppingBag,
  store: Store,
  warehouse: Warehouse,
  factory: Factory,
  business: Building,
  account_balance: Landmark,
  castle: Castle,
  church: Church,
  school: School,
  local_hospital: Hospital,
  local_pharmacy: Pill,
  immunization: Syringe,
  monitor_heart: Activity,
  psychology: Brain,
  visibility: Eye,
  hearing: Ear,
  emoji_people: Smile,
  sentiment_satisfied: Smile,
  sentiment_dissatisfied: Frown,
  sentiment_neutral: Meh,
  sentiment_very_dissatisfied: Angry,
  sentiment_very_satisfied: Smile,
  mood: Smile,
  mood_bad: Frown,
  sleeping: Sleep,
  local_drink: Coffee,
  emoji_food_beverage: Coffee,
  restaurant_menu: Utensils,
  local_dining: Utensils,
  breakfast_dining: Coffee,
  lunch_dining: Utensils,
  dinner_dining: Utensils,
  takeout_dining: ShoppingBag,
  local_grocery_store: ShoppingCart,
  shopping_cart: ShoppingCart,
  credit_card: CreditCard,
  account_balance_wallet: Wallet,
  paid: DollarSign,
  payments: DollarSign,
  receipt_long: Receipt,
  calculate: Calculator,
  percent: Percent,
  tag: Tag,
  label: Tag,
  new_label: Tag,
  link: Link,
  attach_file: Paperclip,
  attach_money: DollarSign,
  bookmark: Bookmark,
  bookmark_border: Bookmark,
  favorite_border: Heart,
  grade: Star,
  star_border: Star,
  star_half: StarHalf,
  thumb_up: ThumbsUp,
  thumb_down: ThumbsDown,
  mode_comment: MessageSquare,
  chat_bubble: MessageSquare,
  forward_to_inbox: Mail,
  mark_email_read: MailCheck,
  mark_email_unread: MailX,
  add_task: CheckCircle,
  assignment_turned_in: CheckCircle,
  assignment: ClipboardList,
  assignment_ind: ClipboardList,
  event_available: Calendar,
  schedule: Clock,
  update: RefreshCw,
  history: Clock,
  timer: Clock,
  alarm: Bell,
  notifications_active: Bell,
  notifications_off: BellOff,
  notifications_none: Bell,
  notifications: Bell,
  vpn_key: KeyRound,
  lock: Lock,
  lock_open: Unlock,
  shield: Shield,
  verified_user: ShieldCheck,
  gpp_good: ShieldCheck,
  gpp_maybe: ShieldAlert,
  gpp_bad: ShieldOff,
  security: Shield,
  https: Lock,
  no_encryption: Unlock,
  key: KeyRound,
  password: Lock,
  fingerprint: Fingerprint,
  qr_code_2: QrCode,
  qr_code_scanner: ScanLine,
  barcode_reader: Barcode,
  credit_card: CreditCard,
  account_balance_wallet: Wallet,
  local_atm: CreditCard,
  atm: CreditCard,
  contactless: Wifi,
  tap_and_play: Wifi,
  nfc: Wifi,
  radar: Radar,
  rss_feed: Rss,
  podcast: Podcast,
  headphones: Headphones,
  headset: Headset,
  speaker: Speaker,
  volume_up: Volume2,
  volume_down: Volume1,
  volume_off: VolumeX,
  volume_mute: VolumeX,
  mic: Mic,
  mic_off: MicOff,
  music_note: Music,
  library_music: Music2,
  queue_music: Music3,
  playlist_play: Music4,
  play_circle: PlayCircle,
  pause_circle: PauseCircle,
  stop_circle: StopCircle,
  skip_next: SkipForward,
  skip_previous: SkipBack,
  fast_forward: FastForward,
  fast_rewind: Rewind,
  shuffle: Shuffle,
  repeat: Repeat,
  repeat_one: Repeat1,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_back: ArrowLeft,
  arrow_circle_up: ArrowUpCircle,
  arrow_circle_down: ArrowDownCircle,
  arrow_circle_left: ArrowLeftCircle,
  arrow_circle_right: ArrowRightCircle,
  undo: RotateCcw,
  redo: RotateCw,
  refresh: RefreshCw,
  cached: RefreshCw,
  autorenew: RefreshCw,
  sync_problem: RefreshCw,
  power_settings_new: Power,
  power_off: PowerOff,
  bolt: Zap,
  flash_on: Zap,
  flash_off: ZapOff,
  electric_bolt: Zap,
  battery_full: BatteryFull,
  battery_5_bar: BatteryMedium,
  battery_4_bar: BatteryMedium,
  battery_3_bar: BatteryLow,
  battery_2_bar: BatteryLow,
  battery_1_bar: BatteryLow,
  battery_alert: BatteryWarning,
  battery_charging_full: BatteryCharging,
  wifi: Wifi,
  wifi_off: WifiOff,
  bluetooth: Bluetooth,
  bluetooth_searching: BluetoothSearching,
  bluetooth_disabled: BluetoothOff,
  signal_cellular_alt: Signal,
  signal_cellular_4_bar: Signal,
  signal_cellular_3_bar: SignalLow,
  signal_cellular_2_bar: SignalMedium,
  signal_cellular_1_bar: SignalLow,
  signal_cellular_off: SignalZero,
  cast: Cast,
  airplay: Airplay,
  screen_share: Monitor,
  stop_screen_share: MonitorOff,
  layers: Layers,
  dashboard: LayoutGrid,
  view_module: LayoutGrid,
  view_quilt: LayoutGrid,
  widgets: LayoutGrid,
  category: LayoutGrid,
  inventory: Package,
  inventory_2: Package2,
  local_shipping: Truck,
  flight_takeoff: Plane,
  flight_land: Plane,
  train: Train,
  directions_car: Car,
  directions_bike: Bike,
  directions_walk: Walk,
  directions_bus: Bus,
  local_gas_station: Fuel,
  local_parking: ParkingCircle,
  flag: Flag,
  markunread_mailbox: Mail,
  inbox: Inbox,
  archive: Archive,
  delete_sweep: Trash2,
  restore_from_trash: Trash2,
  report_problem: AlertTriangle,
  error_outline: AlertCircle,
  info: Info,
  help_outline: HelpCircle,
  feedback: MessageSquare,
  contact_support: HeadphonesIcon,
  live_help: HelpCircle,
  bug_report: Bug,
  build: Wrench,
  construction: HardHat,
  handman: Wrench,
  engineering: Cog,
  science: FlaskConical,
  biotech: FlaskConical,
  psychology: Brain,
  psychiatry: Brain,
  elderly: Users,
  child_care: Baby,
  wc: Toilet,
  shower: Droplets,
  bathtub: Bath,
  local_hotel: Hotel,
  local_laundry_service: Shirt,
  dry_cleaning: Shirt,
  checkroom: Shirt,
  fitness_center: Dumbbell,
  sports_gymnastics: Dumbbell,
  sports_martial_arts: Swords,
  sports_kabaddi: Swords,
  sports_football: Trophy,
  sports_baseball: Trophy,
  sports_basketball: Trophy,
  sports_soccer: Trophy,
  sports_tennis: Trophy,
  sports_golf: Trophy,
  sports_cricket: Trophy,
  sports_hockey: Trophy,
  sports_rugby: Trophy,
  sports_motorsports: Trophy,
  sports_esports: Gamepad2,
  sports_score: Trophy,
  emoji_events: Trophy,
  military_tech: Award,
  workspace_premium: Award,
  dinner_dining: Utensils,
  local_cafe: Coffee,
  local_bar: Beer,
  local_pizza: Pizza,
  restaurant: Utensils,
  shopping_cart: ShoppingCart,
  storefront: Store,
  point_of_sale: CreditCard,
  payment: CreditCard,
  receipt: Receipt,
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  payments: DollarSign,
  money: Banknote,
  attach_money: DollarSign,
  money_off: DollarSign,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  show_chart: BarChart2,
  bar_chart: BarChart2,
  pie_chart: PieChart,
  analytics: Activity,
  monitoring: Activity,
  speed: Gauge,
  equalizer: BarChart3,
  format_list_bulleted: List,
  format_list_numbered: ListOrdered,
  check_box: CheckSquare,
  radio_button_checked: CircleDot,
  toggle_on: ToggleRight,
  toggle_off: ToggleLeft,
  switch_right: ToggleRight,
  switch_left: ToggleLeft,
  dark_mode: Moon,
  light_mode: Sun,
  brightness_7: Sun,
  brightness_4: Moon,
  contrast: Contrast,
  inversion: RotateCw,
  palette: Palette,
  color_lens: Palette,
  format_paint: Paintbrush,
  brush: Paintbrush,
  pen_tool: PenTool,
  draw: PenTool,
  format_color_text: Type,
  format_size: Type,
  text_fields: Type,
  text_format: Type,
  format_bold: Bold,
  format_italic: Italic,
  format_underlined: Underline,
  strikethrough_s: Strikethrough,
  format_align_left: AlignLeft,
  format_align_center: AlignCenter,
  format_align_right: AlignRight,
  format_align_justify: AlignJustify,
  format_indent_increase: Indent,
  format_indent_decrease: Outdent,
  format_line_spacing: AlignJustify,
  format_paragraph: AlignLeft,
  format_clear: X,
  format_quote: Quote,
  code: Code,
  html: Code,
  javascript: Code,
  typescript: Code,
  terminal: Terminal,
  cmd: Terminal,
  powershell: Terminal,
  git: GitBranch,
  github: Github,
  folder_special: Star,
  folder_shared: Users,
  folder_zip: Archive,
  create_new_folder: FolderPlus,
  drive_file_move: FolderInput,
  drive_file_move_outline: FolderInput,
  cloud_sync: RefreshCw,
  cloud_done: CheckCircle,
  cloud_upload: UploadCloud,
  cloud_download: DownloadCloud,
  cloud_queue: Cloud,
  cloud_off: CloudOff,
  cloud_circle: Circle,
  cloud_upload: UploadCloud,
  cloud_download: DownloadCloud,
  cloud_sync: RefreshCw,
  cloud_done: CheckCircle,
  cloud_off: CloudOff,
  cloud_queue: Cloud,
  cloud_circle: Circle,
  cloud: Cloud,
  insert_drive_file: FileText,
  description: FileText,
  note: FileText,
  sticky_note_2: StickyNote,
  assignment: ClipboardList,
  assignment_ind: ClipboardList,
  assignment_return: ClipboardCheck,
  assignment_returned: ClipboardCheck,
  assignment_late: Clock,
  assignment_turned_in: CheckCircle,
  add_to_drive: HardDrive,
  cloud_upload: UploadCloud,
  cloud_download: DownloadCloud,
  cloud_sync: RefreshCw,
  cloud_done: CheckCircle,
  cloud_off: CloudOff,
  cloud_queue: Cloud,
  cloud_circle: Circle,
  cloud: Cloud,
  insert_drive_file: FileText,
  description: FileText,
  note: FileText,
  sticky_note_2: StickyNote,
  assignment: ClipboardList,
  assignment_ind: ClipboardList,
  assignment_return: ClipboardCheck,
  assignment_returned: ClipboardCheck,
  assignment_late: Clock,
  assignment_turned_in: CheckCircle,
  add_to_drive: HardDrive,
  // 测点管理相关
  folder_open: FolderOpen,
  folder: Folder,
  create_new_folder: FolderPlus,
  delete_forever: Trash2,
  restore: RotateCcw,
  undo: RotateCcw,
  redo: RotateCw,
  refresh: RefreshCw,
  sync: RefreshCw,
  autorenew: RefreshCw,
  cached: RefreshCw,
  loop: Repeat,
  replay: Repeat,
  forward: SkipForward,
  rewind: SkipBack,
  fast_forward: FastForward,
  fast_rewind: Rewind,
  skip_next: SkipForward,
  skip_previous: SkipBack,
  // 数据模型相关
  table_chart: Table2,
  grid_on: Grid3X3,
  view_list: List,
  view_module: LayoutGrid,
  view_quilt: LayoutGrid,
  view_carousel: LayoutGrid,
  view_agenda: List,
  view_day: Calendar,
  view_week: Calendar,
  view_month: Calendar,
  view_timeline: Calendar,
  // 数据标准相关
  policy: FileText,
  rule_folder: Folder,
  verified: CheckCircle,
  gpp_good: ShieldCheck,
  gpp_maybe: ShieldAlert,
  gpp_bad: ShieldOff,
  grade: Star,
  stars: Star,
  trophy: Trophy,
  workspace_premium: Award,
  emoji_events: Trophy,
  military_tech: Award,
  local_police: Shield,
  security: Shield,
  shield: Shield,
  shield_moon: Moon,
  shield: Shield,
}

export const getLucideIcon = (name: string) => {
  return ICON_MAP[name] || null
}

// 通用图标组件
export const Icon = defineComponent({
  name: 'LucideIcon',
  props: {
    name: { type: String, required: true },
    size: { type: [Number, String], default: 20 },
    color: { type: String, default: 'currentColor' }
  },
  setup(props) {
    const iconComponent = computed(() => getLucideIcon(props.name))
    
    return () => {
      if (!iconComponent.value) {
        return null
      }
      return h(iconComponent.value, {
        size: props.size,
        color: props.color
      })
    }
  }
})

export default Icon
