/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { defineComponent, h, computed } from 'vue'
import {
  Activity,
  Airplay,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Anchor,
  Angry,
  Archive,
  ArrowDown,
  ArrowDownCircle,
  ArrowLeft,
  ArrowLeftCircle,
  ArrowRight,
  ArrowRightCircle,
  ArrowUp,
  ArrowUpCircle,
  ArrowUpDown,
  Award,
  Baby,
  Banknote,
  BarChart2,
  BarChart3,
  Barcode,
  Bath,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  BatteryWarning,
  Beer,
  Bell,
  BellOff,
  Bike,
  Bluetooth,
  BluetoothOff,
  BluetoothSearching,
  Bold,
  Bookmark,
  Bot,
  Brain,
  Bug,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Car,
  Cast,
  Castle,
  Cat,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  Church,
  Circle,
  CircleDot,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudOff,
  Code,
  Coffee,
  Cog,
  Compass,
  Component,
  Contrast,
  Copy,
  CreditCard,
  Database,
  DollarSign,
  Download,
  DownloadCloud,
  Droplet,
  Droplets,
  Dumbbell,
  Ear,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  Factory,
  FastForward,
  FileCode,
  FileJson,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Folder,
  FolderInput,
  FolderOpen,
  FolderPlus,
  Frown,
  Fuel,
  Gamepad2,
  Gauge,
  Gift,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Globe,
  Grid,
  Grid3X3,
  HardDrive,
  HardHat,
  Headphones,
  HeadphonesIcon,
  Headset,
  Heart,
  HelpCircle,
  Hexagon,
  Home,
  Hospital,
  Hotel,
  Image,
  Inbox,
  Indent,
  Info,
  Italic,
  KeyRound,
  Landmark,
  Layers,
  LayoutGrid,
  Leaf,
  Link,
  List,
  ListOrdered,
  Lock,
  Magnet,
  Mail,
  MailCheck,
  MailX,
  MapPin,
  Meh,
  Menu,
  MessageSquare,
  Mic,
  MicOff,
  Minus,
  Monitor,
  MonitorOff,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Music,
  Music2,
  Music3,
  Music4,
  Navigation,
  Network,
  Outdent,
  Package,
  Package2,
  Paintbrush,
  Palette,
  Paperclip,
  ParkingCircle,
  PauseCircle,
  PenTool,
  Pencil,
  Percent,
  Phone,
  PieChart,
  Pill,
  Pizza,
  Plane,
  PlayCircle,
  Plus,
  Podcast,
  Power,
  PowerOff,
  QrCode,
  Quote,
  Radar,
  Receipt,
  RefreshCw,
  Repeat,
  Repeat1,
  Rewind,
  RotateCcw,
  RotateCw,
  Rss,
  Save,
  ScanLine,
  School,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Signal,
  SignalLow,
  SignalMedium,
  SignalZero,
  SkipBack,
  SkipForward,
  Sliders,
  Smile,
  Snowflake,
  Sparkles,
  Speaker,
  Square,
  Star,
  StarHalf,
  StickyNote,
  StopCircle,
  Store,
  Strikethrough,
  Sun,
  Sunrise,
  Sunset,
  Swords,
  Syringe,
  Table2,
  Tag,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  ToggleRight,
  Toilet,
  Train,
  Trash2,
  TreePine,
  TrendingDown,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Type,
  Underline,
  Unlock,
  Upload,
  UploadCloud,
  Users,
  Utensils,
  Volume1,
  Volume2,
  VolumeX,
  Wallet,
  Wand2,
  Warehouse,
  Wifi,
  WifiOff,
  Wine,
  Wrench,
  X,
  Zap,
  ZapOff,
} from 'lucide-vue-next'

// Material Icons 到 Lucide 图标的映射
const ICON_MAP: Record<string, any> = {
  add: Plus,
  search: Search,
  edit: Edit3,
  edit_square: Edit3,
  delete: Trash2,
  delete_outline: Trash2,
  content_copy: Copy,
  check_circle: CheckCircle,
  check_circle_outline: CheckCircle,
  pause_circle_outline: PauseCircle,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  upload: Upload,
  upload_file: Upload,
  download: Download,
  download_done: Download,
  database: Database,
  home: Home,
  close: X,
  info_outline: Info,
  warning: AlertTriangle,
  warning_amber: AlertTriangle,
  check: Check,
  remove: Minus,
  settings: Settings,
  settings_suggest: Settings,
  file_open: FileJson,
  upload_cloud: UploadCloud,
  download_cloud: DownloadCloud,
  component: Component,
  help: HelpCircle,
  image: Image,
  close_fullscreen: X,
  list: List,
  grid_view: Grid,
  sparkles: Sparkles,
  precision_manufacturing: Settings,
  move_up: Upload,
  api: Globe,
  sell: Tag,
  account_tree: Network,
  corporate_fare: Building2,
  hub: Network,
  dns: Database,
  travel_explore: Compass,
  menu: Menu,
  tune: Sliders,
  file_code: FileCode,
  save: Save,
  send: Send,
  email: Mail,
  phone: Phone,
  chat: MessageSquare,
  event: Calendar,
  place: MapPin,
  star: Star,
  favorite: Heart,
  share: Share2,
  open_in_new: ExternalLink,
  visibility_off: EyeOff,
  filter_list: Filter,
  sort: ArrowUpDown,
  more_vert: MoreVertical,
  more_horiz: MoreHorizontal,
  error: AlertCircle,
  circle: Circle,
  crop_square: Square,
  change_history: Triangle,
  hexagon: Hexagon,
  blur_on: Circle,
  scatter_plot: Circle,
  bubbles: Circle,
  local_fire_department: Flame,
  water_drop: Droplet,
  eco: Leaf,
  forest: TreePine,
  yard: Flower2,
  pets: Cat,
  smart_toy: Bot,
  magnet: Magnet,
  auto_fix_high: Wand2,
  edit_note: Pencil,
  title: Type,
  format_strikethrough: Strikethrough,
  git_branch: GitBranch,
  commit: GitCommit,
  merge_type: GitMerge,
  pull_request: GitPullRequest,
  device_thermostat: Thermometer,
  humidity_percent: Droplets,
  ac_unit: Snowflake,
  wb_sunny: Sun,
  nightlight: Moon,
  wb_twilight: Sunrise,
  sunset: Sunset,
  pin_drop: MapPin,
  navigation: Navigation,
  explore: Compass,
  anchor: Anchor,
  directions_boat: Ship,
  flight: Plane,
  wine_bar: Wine,
  cake: Cake,
  redeem: Gift,
  shopping_bag: ShoppingBag,
  store: Store,
  warehouse: Warehouse,
  factory: Factory,
  business: Building,
  castle: Castle,
  church: Church,
  school: School,
  local_hospital: Hospital,
  local_pharmacy: Pill,
  immunization: Syringe,
  monitor_heart: Activity,
  visibility: Eye,
  hearing: Ear,
  emoji_people: Smile,
  sentiment_satisfied: Smile,
  sentiment_dissatisfied: Frown,
  sentiment_neutral: Meh,
  sentiment_very_dissatisfied: Angry,
  sentiment_very_satisfied: Smile,
  mood: Smile,
  mood_bad: Frown,
  local_drink: Coffee,
  emoji_food_beverage: Coffee,
  restaurant_menu: Utensils,
  local_dining: Utensils,
  breakfast_dining: Coffee,
  lunch_dining: Utensils,
  takeout_dining: ShoppingBag,
  local_grocery_store: ShoppingCart,
  paid: DollarSign,
  receipt_long: Receipt,
  calculate: Calculator,
  percent: Percent,
  tag: Tag,
  label: Tag,
  new_label: Tag,
  link: Link,
  attach_file: Paperclip,
  bookmark: Bookmark,
  bookmark_border: Bookmark,
  favorite_border: Heart,
  star_border: Star,
  star_half: StarHalf,
  thumb_up: ThumbsUp,
  thumb_down: ThumbsDown,
  mode_comment: MessageSquare,
  chat_bubble: MessageSquare,
  forward_to_inbox: Mail,
  mark_email_read: MailCheck,
  mark_email_unread: MailX,
  add_task: CheckCircle,
  event_available: Calendar,
  schedule: Clock,
  update: RefreshCw,
  history: Clock,
  timer: Clock,
  alarm: Bell,
  notifications_active: Bell,
  notifications_off: BellOff,
  notifications_none: Bell,
  notifications: Bell,
  vpn_key: KeyRound,
  lock: Lock,
  lock_open: Unlock,
  verified_user: ShieldCheck,
  https: Lock,
  no_encryption: Unlock,
  key: KeyRound,
  password: Lock,
  fingerprint: Fingerprint,
  qr_code_2: QrCode,
  qr_code_scanner: ScanLine,
  barcode_reader: Barcode,
  credit_card: CreditCard,
  local_atm: CreditCard,
  atm: CreditCard,
  contactless: Wifi,
  tap_and_play: Wifi,
  nfc: Wifi,
  radar: Radar,
  rss_feed: Rss,
  podcast: Podcast,
  headphones: Headphones,
  headset: Headset,
  speaker: Speaker,
  volume_up: Volume2,
  volume_down: Volume1,
  volume_off: VolumeX,
  volume_mute: VolumeX,
  mic: Mic,
  mic_off: MicOff,
  music_note: Music,
  library_music: Music2,
  queue_music: Music3,
  playlist_play: Music4,
  play_circle: PlayCircle,
  pause_circle: PauseCircle,
  stop_circle: StopCircle,
  shuffle: Shuffle,
  repeat: Repeat,
  repeat_one: Repeat1,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_back: ArrowLeft,
  arrow_circle_up: ArrowUpCircle,
  arrow_circle_down: ArrowDownCircle,
  arrow_circle_left: ArrowLeftCircle,
  arrow_circle_right: ArrowRightCircle,
  sync_problem: RefreshCw,
  power_settings_new: Power,
  power_off: PowerOff,
  bolt: Zap,
  flash_on: Zap,
  flash_off: ZapOff,
  electric_bolt: Zap,
  battery_full: BatteryFull,
  battery_5_bar: BatteryMedium,
  battery_4_bar: BatteryMedium,
  battery_3_bar: BatteryLow,
  battery_2_bar: BatteryLow,
  battery_1_bar: BatteryLow,
  battery_alert: BatteryWarning,
  battery_charging_full: BatteryCharging,
  wifi: Wifi,
  wifi_off: WifiOff,
  bluetooth: Bluetooth,
  bluetooth_searching: BluetoothSearching,
  bluetooth_disabled: BluetoothOff,
  signal_cellular_alt: Signal,
  signal_cellular_4_bar: Signal,
  signal_cellular_3_bar: SignalLow,
  signal_cellular_2_bar: SignalMedium,
  signal_cellular_1_bar: SignalLow,
  signal_cellular_off: SignalZero,
  cast: Cast,
  airplay: Airplay,
  screen_share: Monitor,
  stop_screen_share: MonitorOff,
  layers: Layers,
  dashboard: LayoutGrid,
  widgets: LayoutGrid,
  category: LayoutGrid,
  inventory: Package,
  inventory_2: Package2,
  local_shipping: Truck,
  flight_takeoff: Plane,
  flight_land: Plane,
  train: Train,
  directions_car: Car,
  directions_bike: Bike,
  directions_bus: Bus,
  local_gas_station: Fuel,
  local_parking: ParkingCircle,
  flag: Flag,
  markunread_mailbox: Mail,
  inbox: Inbox,
  archive: Archive,
  delete_sweep: Trash2,
  restore_from_trash: Trash2,
  report_problem: AlertTriangle,
  error_outline: AlertCircle,
  info: Info,
  help_outline: HelpCircle,
  feedback: MessageSquare,
  contact_support: HeadphonesIcon,
  live_help: HelpCircle,
  bug_report: Bug,
  build: Wrench,
  construction: HardHat,
  handman: Wrench,
  engineering: Cog,
  science: FlaskConical,
  biotech: FlaskConical,
  psychology: Brain,
  psychiatry: Brain,
  elderly: Users,
  child_care: Baby,
  wc: Toilet,
  shower: Droplets,
  bathtub: Bath,
  local_hotel: Hotel,
  local_laundry_service: Shirt,
  dry_cleaning: Shirt,
  checkroom: Shirt,
  fitness_center: Dumbbell,
  sports_gymnastics: Dumbbell,
  sports_martial_arts: Swords,
  sports_kabaddi: Swords,
  sports_football: Trophy,
  sports_baseball: Trophy,
  sports_basketball: Trophy,
  sports_soccer: Trophy,
  sports_tennis: Trophy,
  sports_golf: Trophy,
  sports_cricket: Trophy,
  sports_hockey: Trophy,
  sports_rugby: Trophy,
  sports_motorsports: Trophy,
  sports_esports: Gamepad2,
  sports_score: Trophy,
  dinner_dining: Utensils,
  local_cafe: Coffee,
  local_bar: Beer,
  local_pizza: Pizza,
  restaurant: Utensils,
  shopping_cart: ShoppingCart,
  storefront: Store,
  point_of_sale: CreditCard,
  payment: CreditCard,
  receipt: Receipt,
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  payments: DollarSign,
  money: Banknote,
  attach_money: DollarSign,
  money_off: DollarSign,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  show_chart: BarChart2,
  bar_chart: BarChart2,
  pie_chart: PieChart,
  analytics: Activity,
  monitoring: Activity,
  speed: Gauge,
  equalizer: BarChart3,
  format_list_bulleted: List,
  format_list_numbered: ListOrdered,
  check_box: CheckSquare,
  radio_button_checked: CircleDot,
  toggle_on: ToggleRight,
  toggle_off: ToggleLeft,
  switch_right: ToggleRight,
  switch_left: ToggleLeft,
  dark_mode: Moon,
  light_mode: Sun,
  brightness_7: Sun,
  brightness_4: Moon,
  contrast: Contrast,
  inversion: RotateCw,
  palette: Palette,
  color_lens: Palette,
  format_paint: Paintbrush,
  brush: Paintbrush,
  pen_tool: PenTool,
  draw: PenTool,
  format_color_text: Type,
  format_size: Type,
  text_fields: Type,
  text_format: Type,
  format_bold: Bold,
  format_italic: Italic,
  format_underlined: Underline,
  strikethrough_s: Strikethrough,
  format_align_left: AlignLeft,
  format_align_center: AlignCenter,
  format_align_right: AlignRight,
  format_align_justify: AlignJustify,
  format_indent_increase: Indent,
  format_indent_decrease: Outdent,
  format_line_spacing: AlignJustify,
  format_paragraph: AlignLeft,
  format_clear: X,
  format_quote: Quote,
  code: Code,
  html: Code,
  javascript: Code,
  typescript: Code,
  terminal: Terminal,
  cmd: Terminal,
  powershell: Terminal,
  git: GitBranch,
  github: Github,
  folder_special: Star,
  folder_shared: Users,
  folder_zip: Archive,
  drive_file_move: FolderInput,
  drive_file_move_outline: FolderInput,
  cloud_upload: UploadCloud,
  cloud_download: DownloadCloud,
  cloud_sync: RefreshCw,
  cloud_done: CheckCircle,
  cloud_off: CloudOff,
  cloud_queue: Cloud,
  cloud_circle: Circle,
  cloud: Cloud,
  insert_drive_file: FileText,
  description: FileText,
  note: FileText,
  sticky_note_2: StickyNote,
  assignment: ClipboardList,
  assignment_ind: ClipboardList,
  assignment_return: ClipboardCheck,
  assignment_returned: ClipboardCheck,
  assignment_late: Clock,
  assignment_turned_in: CheckCircle,
  add_to_drive: HardDrive,
  // 测点管理相关
  folder_open: FolderOpen,
  folder: Folder,
  create_new_folder: FolderPlus,
  delete_forever: Trash2,
  restore: RotateCcw,
  undo: RotateCcw,
  redo: RotateCw,
  refresh: RefreshCw,
  sync: RefreshCw,
  autorenew: RefreshCw,
  cached: RefreshCw,
  loop: Repeat,
  replay: Repeat,
  forward: SkipForward,
  rewind: SkipBack,
  fast_forward: FastForward,
  fast_rewind: Rewind,
  skip_next: SkipForward,
  skip_previous: SkipBack,
  // 数据模型相关
  table_chart: Table2,
  grid_on: Grid3X3,
  view_list: List,
  view_module: LayoutGrid,
  view_quilt: LayoutGrid,
  view_carousel: LayoutGrid,
  view_agenda: List,
  view_day: Calendar,
  view_week: Calendar,
  view_month: Calendar,
  view_timeline: Calendar,
  // 数据标准相关
  policy: FileText,
  rule_folder: Folder,
  verified: CheckCircle,
  gpp_good: ShieldCheck,
  gpp_maybe: ShieldAlert,
  gpp_bad: ShieldOff,
  grade: Star,
  stars: Star,
  trophy: Trophy,
  workspace_premium: Award,
  emoji_events: Trophy,
  military_tech: Award,
  local_police: Shield,
  security: Shield,
  shield_moon: Moon,
  shield: Shield
}

export const getLucideIcon = (name: string) => {
  return ICON_MAP[name] || null
}

// 通用图标组件
export const Icon = defineComponent({
  name: 'LucideIcon',
  props: {
    name: { type: String, required: true },
    size: { type: [Number, String], default: 20 },
    color: { type: String, default: 'currentColor' }
  },
  setup(props) {
    const iconComponent = computed(() => getLucideIcon(props.name))

    return () => {
      if (!iconComponent.value) {
        return null
      }
      return h(iconComponent.value, {
        size: props.size,
        color: props.color
      })
    }
  }
})

export default Icon
