/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { defineComponent, h, computed } from 'vue'
import {
  Plus,
  Search,
  Edit3,
  Trash2,
  Copy,
  CheckCircle,
  PauseCircle,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  FolderOpen,
  Folder,
  Upload,
  Download,
  Database,
  RefreshCw,
  Home,
  ArrowBack,
  Close,
  Info,
  AlertTriangle,
  Check,
  Minus,
  Settings,
  FileJson,
  UploadCloud,
  DownloadCloud,
  Component,
  HelpCircle,
  Image,
  X,
  List,
  Grid,
  Tag,
  Globe,
  Network,
  Bot,
  Building2,
  KeyRound,
  ShieldCheck,
  Activity,
  Compass,
  FolderOff,
  DatabaseOff,
  Menu,
  Sliders,
  Code,
  FileCode,
  Save,
  Send,
  Mail,
  Phone,
  MessageSquare,
  Bell,
  BellOff,
  Calendar,
  Clock,
  MapPin,
  Star,
  Heart,
  Bookmark,
  Share2,
  ExternalLink,
  Link,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Filter,
  MoreVertical,
  MoreHorizontal,
  AlertCircle,
  Circle,
  CircleDot,
  Square,
  Triangle,
  Hexagon,
  Flame,
  Droplet,
  Leaf,
  TreePine,
  Flower2,
  Bug,
  Cat,
  Bot as BotIcon,
  Magnet,
  Wand2,
  Paintbrush,
  PenTool,
  Pencil,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Indent,
  Outdent,
  ListOrdered,
  Quote,
  Terminal,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Cloud,
  CloudOff,
  Thermometer,
  Droplets,
  Snowflake,
  Sunrise,
  Sunset,
  Navigation,
  Anchor,
  Ship,
  Plane,
  Train,
  Car,
  Bike,
  Walk,
  Bus,
  Fuel,
  ParkingCircle,
  Coffee,
  Utensils,
  Pizza,
  Beer,
  Wine,
  Cake,
  Gift,
  ShoppingBag,
  Store,
  Warehouse,
  Factory,
  Building,
  Landmark,
  School,
  Hospital,
  Pill,
  Syringe,
  Activity as ActivityIcon,
  Brain,
  Ear,
  Smile,
  Frown,
  Meh,
  Angry,
  Sleep,
  Dizzy,
  LayoutGrid,
  LayoutList,
  Table2,
  Grid3X3,
  FileText,
  StickyNote,
  ClipboardList,
  ClipboardCheck,
  HardDrive,
  Wrench,
  Cog,
  FlaskConical,
  Users,
  Baby,
  Dumbbell,
  Swords,
  Trophy,
  Award,
  Gamepad2,
  Gauge,
  BarChart2,
  PieChart,
  BarChart3,
  TrendingUp,
  TrendingDown,
  Contrast,
  Palette,
  Network as NetworkIcon,
  ScanLine,
  QrCode,
  Barcode,
  CreditCard,
  Wallet,
  Banknote,
  DollarSign,
  Percent,
  Hash,
  Paperclip,
  Radio,
  Podcast,
  Headphones,
  Headset,
  Speaker,
  Volume2,
  Volume1,
  VolumeX,
  Mic,
  MicOff,
  Music,
  Music2,
  Music3,
  Music4,
  PlayCircle,
  StopCircle,
  SkipForward,
  SkipBack,
  Rewind,
  FastForward,
  Shuffle,
  Repeat,
  Repeat1,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpCircle,
  ArrowDownCircle,
  ArrowLeftCircle,
  ArrowRightCircle,
  RotateCcw,
  RotateCw,
  Power,
  PowerOff,
  Zap,
  ZapOff,
  BatteryFull,
  BatteryMedium,
  BatteryLow,
  BatteryWarning,
  BatteryCharging,
  Wifi,
  WifiOff,
  Bluetooth,
  BluetoothOff,
  Signal,
  Cast,
  Monitor,
  MonitorOff,
  Package,
  Package2,
  Truck,
  Compass as CompassIcon,
  Flag,
  Inbox,
  Archive,
  Shield,
  ShieldAlert,
  ShieldOff,
  KeyRound as KeyRoundIcon,
  Fingerprint,
  Box,
  Layers,
  Map,
  Globe2,
  Navigation2,
  RefreshCcw,
  Loader,
  Loader2,
  FolderPlus,
  FolderInput,
  Trash2 as TrashIcon,
  RotateCcw as UndoIcon,
  RotateCw as RedoIcon,
  Repeat as LoopIcon,
  Repeat as ReplayIcon,
  SkipForward as ForwardIcon,
  SkipBack as RewindIcon,
  FastForward as FastForwardIcon,
  FastRewind,
  FileCode2,
  LayoutTemplate,
  LayoutDashboard,
  LayoutList as LayoutListIcon,
  LayoutGrid as LayoutGridIcon,
  LayoutTemplate as LayoutTemplateIcon,
  LayoutDashboard as LayoutDashboardIcon,
  CalendarDays,
  CalendarClock,
  CalendarCheck,
  CalendarX,
  Clock3,
  Clock4,
  Clock5,
  Clock6,
  Clock7,
  Clock8,
  Clock9,
  Clock10,
  Clock11,
  Clock12,
  Timer,
  Hourglass,
  HourglassIcon,
  Sand,
  SandIcon,
  HourglassIcon as HourglassIcon2,
  Sand as SandIcon2,
  HourglassIcon as HourglassIcon3,
  Sand as SandIcon3,
  HourglassIcon as HourglassIcon4,
  Sand as SandIcon4,
  HourglassIcon as HourglassIcon5,
  Sand as SandIcon5,
  HourglassIcon as HourglassIcon6,
  Sand as SandIcon6,
  HourglassIcon as HourglassIcon7,
  Sand as SandIcon7,
  HourglassIcon as HourglassIcon8,
  Sand as SandIcon8,
  HourglassIcon as HourglassIcon9,
  Sand as SandIcon9,
  HourglassIcon as HourglassIcon10,
  Sand as SandIcon10,
  HourglassIcon as HourglassIcon11,
  Sand as SandIcon11,
  HourglassIcon as HourglassIcon12,
  Sand as SandIcon12
} from 'lucide-vue-next'

// Material Icons 到 Lucide 图标的映射
const ICON_MAP: Record<string, any> = {
  // 通用
  add: Plus,
  search: Search,
  edit: Edit3,
  edit_square: Edit3,
  delete: Trash2,
  delete_outline: Trash2,
  delete_forever: Trash2,
  content_copy: Copy,
  check_circle: CheckCircle,
  check_circle_outline: CheckCircle,
  pause_circle: PauseCircle,
  pause_circle_outline: PauseCircle,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  chevron_up: ChevronUp,
  chevron_down: ChevronDown,
  folder_open: FolderOpen,
  folder: Folder,
  create_new_folder: FolderPlus,
  upload: Upload,
  upload_file: Upload,
  download: Download,
  download_done: Download,
  database: Database,
  sync: RefreshCw,
  refresh: RefreshCw,
  autorenew: RefreshCw,
  cached: RefreshCw,
  home: Home,
  arrow_back: ArrowBack,
  close: Close,
  info: Info,
  info_outline: Info,
  warning: AlertTriangle,
  warning_amber: AlertTriangle,
  check: Check,
  remove: Minus,
  settings: Settings,
  settings_suggest: Settings,
  file_open: FileJson,
  upload_cloud: UploadCloud,
  download_cloud: DownloadCloud,
  component: Component,
  help: HelpCircle,
  help_outline: HelpCircle,
  image: Image,
  close_fullscreen: X,
  list: List,
  grid_view: Grid,
  menu: Menu,
  tune: Sliders,
  code: Code,
  file_code: FileCode,
  save: Save,
  send: Send,

  // 数据源相关
  precision_manufacturing: Settings,
  move_up: Upload,
  api: Globe,
  sell: Tag,
  dns: Database,
  travel_explore: Compass,
  folder_off: FolderOff,
  database_off: DatabaseOff,

  // 导航相关
  account_tree: Network,
  hub: Network,

  // AI相关
  smart_toy: Bot,

  // 管理相关
  corporate_fare: Building2,
  key: KeyRound,
  verified_user: ShieldCheck,
  monitoring: Activity,

  // 通讯相关
  email: Mail,
  phone: Phone,
  chat: MessageSquare,
  notifications: Bell,
  notifications_active: Bell,
  notifications_off: BellOff,
  notifications_none: Bell,

  // 时间相关
  event: Calendar,
  schedule: Clock,

  // 位置相关
  place: MapPin,

  // 收藏相关
  star: Star,
  favorite: Heart,
  favorite_border: Heart,
  bookmark: Bookmark,
  bookmark_border: Bookmark,
  share: Share2,
  open_in_new: ExternalLink,
  link: Link,

  // 安全相关
  lock: Lock,
  lock_open: Unlock,
  visibility: Eye,
  visibility_off: EyeOff,

  // 排序相关
  filter_list: Filter,
  sort: ArrowUp,
  more_vert: MoreVertical,
  more_horiz: MoreHorizontal,

  // 状态相关
  error: AlertCircle,
  circle: Circle,
  crop_square: Square,
  change_history: Triangle,
  hexagon: Hexagon,

  // 自然相关
  local_fire_department: Flame,
  water_drop: Droplet,
  eco: Leaf,
  forest: TreePine,
  yard: Flower2,
  bug_report: Bug,
  pets: Cat,
  magnet: Magnet,

  // 工具相关
  auto_fix_high: Wand2,
  brush: Paintbrush,
  format_paint: Paintbrush,
  pen_tool: PenTool,
  edit_note: Pencil,

  // 文本相关
  title: Type,
  format_bold: Bold,
  format_italic: Italic,
  format_underlined: Underline,
  format_strikethrough: Strikethrough,
  format_align_left: AlignLeft,
  format_align_center: AlignCenter,
  format_align_right: AlignRight,
  format_align_justify: AlignJustify,
  format_indent_increase: Indent,
  format_indent_decrease: Outdent,
  format_list_numbered: ListOrdered,
  format_quote: Quote,
  terminal: Terminal,

  // 版本控制相关
  git_branch: GitBranch,
  commit: GitCommit,
  merge_type: GitMerge,
  pull_request: GitPullRequest,

  // 天气相关
  cloud: Cloud,
  cloud_queue: Cloud,
  cloud_off: CloudOff,
  device_thermostat: Thermometer,
  humidity_percent: Droplets,
  ac_unit: Snowflake,
  wb_sunny: Sunrise,
  dark_mode: Sunset,
  nightlight: Moon,
  light_mode: Sun,

  // 交通相关
  pin_drop: MapPin,
  navigation: Navigation,
  explore: Compass,
  anchor: Anchor,
  directions_boat: Ship,
  flight: Plane,
  train: Train,
  directions_car: Car,
  directions_bike: Bike,
  directions_walk: Walk,
  directions_bus: Bus,
  local_gas_station: Fuel,
  local_parking: ParkingCircle,

  // 餐饮相关
  local_cafe: Coffee,
  restaurant: Utensils,
  local_pizza: Pizza,
  local_bar: Beer,
  wine_bar: Wine,
  cake: Cake,

  // 购物相关
  redeem: Gift,
  shopping_bag: ShoppingBag,
  shopping_cart: ShoppingBag,
  store: Store,
  warehouse: Warehouse,
  factory: Factory,
  business: Building,

  // 建筑相关
  account_balance: Landmark,
  castle: Landmark,
  church: Landmark,
  school: School,
  local_hospital: Hospital,

  // 医疗相关
  local_pharmacy: Pill,
  immunization: Syringe,
  monitor_heart: Activity,
  psychology: Brain,
  hearing: Ear,

  // 表情相关
  emoji_people: Smile,
  sentiment_satisfied: Smile,
  sentiment_dissatisfied: Frown,
  sentiment_neutral: Meh,
  sentiment_very_dissatisfied: Angry,
  sentiment_very_satisfied: Smile,
  mood: Smile,
  mood_bad: Frown,
  sleeping: Sleep,
  dizzy: Dizzy,

  // 食物相关
  local_drink: Coffee,
  emoji_food_beverage: Coffee,
  restaurant_menu: Utensils,
  local_dining: Utensils,
  breakfast_dining: Coffee,
  lunch_dining: Utensils,
  dinner_dining: Utensils,
  takeout_dining: ShoppingBag,
  local_grocery_store: ShoppingBag,

  // 支付相关
  credit_card: CreditCard,
  account_balance_wallet: Wallet,
  paid: DollarSign,
  payments: DollarSign,
  receipt_long: Receipt,
  calculate: Calculator,
  percent: Percent,
  tag: Tag,
  label: Tag,

  // 通知相关
  forward_to_inbox: Mail,
  mark_email_read: Mail,
  mark_email_unread: Mail,
  add_task: CheckCircle,
  assignment_turned_in: CheckCircle,
  assignment: ClipboardList,
  assignment_ind: ClipboardList,

  // 安全相关
  shield: Shield,
  gpp_good: ShieldCheck,
  gpp_maybe: ShieldAlert,
  gpp_bad: ShieldOff,
  security: Shield,
  https: Lock,
  no_encryption: Unlock,
  password: Lock,
  fingerprint: Fingerprint,

  // 二维码相关
  qr_code_2: QrCode,
  qr_code_scanner: ScanLine,
  barcode_reader: Barcode,

  // 媒体相关
  contactless: Wifi,
  tap_and_play: Wifi,
  nfc: Wifi,
  radar: Signal,
  rss_feed: Signal,
  podcast: Signal,
  headphones: Headphones,
  headset: Headset,
  speaker: Speaker,
  volume_up: Volume2,
  volume_down: Volume1,
  volume_off: VolumeX,
  volume_mute: VolumeX,
  mic: Mic,
  mic_off: MicOff,
  music_note: Music,
  library_music: Music2,
  queue_music: Music3,
  playlist_play: Music4,
  play_circle: PlayCircle,
  pause_circle: PauseCircle,
  stop_circle: StopCircle,
  skip_next: SkipForward,
  skip_previous: SkipBack,
  fast_forward: FastForward,
  fast_rewind: Rewind,
  shuffle: Shuffle,
  repeat: Repeat,
  repeat_one: Repeat1,

  // 箭头相关
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_circle_up: ArrowUpCircle,
  arrow_circle_down: ArrowDownCircle,
  arrow_circle_left: ArrowLeftCircle,
  arrow_circle_right: ArrowRightCircle,
  undo: RotateCcw,
  redo: RotateCw,

  // 电源相关
  power_settings_new: Power,
  power_off: PowerOff,
  bolt: Zap,
  flash_on: Zap,
  flash_off: ZapOff,
  electric_bolt: Zap,

  // 电池相关
  battery_full: BatteryFull,
  battery_5_bar: BatteryMedium,
  battery_4_bar: BatteryMedium,
  battery_3_bar: BatteryLow,
  battery_2_bar: BatteryLow,
  battery_1_bar: BatteryLow,
  battery_alert: BatteryWarning,
  battery_charging_full: BatteryCharging,

  // 网络相关
  wifi: Wifi,
  wifi_off: WifiOff,
  bluetooth: Bluetooth,
  bluetooth_searching: Bluetooth,
  bluetooth_disabled: BluetoothOff,
  signal_cellular_alt: Signal,
  signal_cellular_4_bar: Signal,
  signal_cellular_3_bar: Signal,
  signal_cellular_2_bar: Signal,
  signal_cellular_1_bar: Signal,
  signal_cellular_off: Signal,
  cast: Cast,
  airplay: Cast,
  screen_share: Monitor,
  stop_screen_share: MonitorOff,

  // 布局相关
  layers: Layers,
  dashboard: LayoutGrid,
  view_module: LayoutGrid,
  view_quilt: LayoutGrid,
  widgets: LayoutGrid,
  category: LayoutGrid,

  // 包相关
  inventory: Package,
  inventory_2: Package2,
  local_shipping: Truck,
  flight_takeoff: Plane,
  flight_land: Plane,

  // 标记相关
  flag: Flag,
  markunread_mailbox: Mail,
  inbox: Inbox,
  archive: Archive,
  delete_sweep: Trash2,
  restore_from_trash: Trash2,

  // 反馈相关
  report_problem: AlertTriangle,
  error_outline: AlertCircle,
  feedback: MessageSquare,
  contact_support: Headphones,
  live_help: HelpCircle,
  bug_report: Bug,

  // 工具相关
  build: Wrench,
  construction: Wrench,
  handman: Wrench,
  engineering: Cog,
  science: FlaskConical,
  biotech: FlaskConical,
  psychology: Brain,
  psychiatry: Brain,

  // 用户相关
  elderly: Users,
  child_care: Users,

  // 运动相关
  fitness_center: Dumbbell,
  sports_gymnastics: Dumbbell,
  sports_martial_arts: Swords,
  sports_football: Trophy,
  sports_baseball: Trophy,
  sports_basketball: Trophy,
  sports_soccer: Trophy,
  sports_tennis: Trophy,
  sports_golf: Trophy,
  sports_cricket: Trophy,
  sports_hockey: Trophy,
  sports_rugby: Trophy,
  sports_motorsports: Trophy,
  sports_esports: Gamepad2,
  sports_score: Trophy,
  emoji_events: Trophy,
  military_tech: Award,
  workspace_premium: Award,

  // 图表相关
  show_chart: BarChart2,
  bar_chart: BarChart2,
  pie_chart: PieChart,
  analytics: Activity,
  speed: Gauge,
  equalizer: BarChart3,
  trending_up: TrendingUp,
  trending_down: TrendingDown,

  // 格式相关
  format_list_bulleted: List,
  check_box: CheckSquare,
  radio_button_checked: CircleDot,
  toggle_on: ToggleRight,
  toggle_off: ToggleLeft,

  // 主题相关
  brightness_7: Sun,
  brightness_4: Moon,
  contrast: Contrast,
  inversion: RotateCw,
  palette: Palette,
  color_lens: Palette,
  format_color_text: Type,
  format_size: Type,
  text_fields: Type,
  text_format: Type,
  format_line_spacing: AlignJustify,
  format_paragraph: AlignLeft,
  format_clear: X,
  html: Code,
  javascript: Code,
  typescript: Code,
  cmd: Terminal,
  powershell: Terminal,
  git: GitBranch,
  github: Github,

  // 文件相关
  folder_special: Star,
  folder_shared: Users,
  folder_zip: Archive,
  drive_file_move: FolderInput,
  cloud_sync: RefreshCw,
  cloud_done: CheckCircle,
  cloud_circle: Circle,
  insert_drive_file: FileText,
  description: FileText,
  note: FileText,
  sticky_note_2: StickyNote,
  assignment_return: ClipboardCheck,
  assignment_returned: ClipboardCheck,
  assignment_late: Clock,
  add_to_drive: HardDrive,

  // 刷新相关
  loop: Repeat,
  replay: Repeat,
  forward: SkipForward,
  rewind: Rewind,

  // 数据模型相关
  table_chart: Table2,
  grid_on: Grid3X3,
  view_list: List,
  view_carousel: LayoutGrid,
  view_agenda: List,
  view_day: Calendar,
  view_week: Calendar,
  view_month: Calendar,
  view_timeline: Calendar,

  // 数据标准相关
  policy: FileText,
  rule_folder: Folder,
  verified: CheckCircle,
  grade: Star,
  stars: Star,
  trophy: Trophy,
  local_police: Shield,
  shield_moon: Moon,

  // 设置相关
  tune: Sliders,
  equalizer: BarChart3,

  // 测点管理相关
  create_new_folder: FolderPlus,
  restore: RotateCcw,
  sync_problem: RefreshCw
}

export const getLucideIcon = (name: string) => {
  return ICON_MAP[name] || null
}

// 通用图标组件
export const Icon = defineComponent({
  name: 'LucideIcon',
  props: {
    name: { type: String, required: true },
    size: { type: [Number, String], default: 20 },
    color: { type: String, default: 'currentColor' }
  },
  setup(props) {
    const iconComponent = computed(() => getLucideIcon(props.name))

    return () => {
      if (!iconComponent.value) {
        return null
      }
      return h(iconComponent.value, {
        size: props.size,
        color: props.color
      })
    }
  }
})

export default Icon
